language: java
jdk: oraclejdk8
install: true

before_install:
  - chmod +x mvnw
script:
  - ./mvnw clean install -B

services:
  - docker  
  
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build onulo/todo-app .
- docker push onulo/todo-app
 